### ISSUE TITLE
Typos on your portfolio.

### ISSUE THREAD

**Issue by BrunoJurkovic** [champ96k/champ96k.github.io#5]
Hello there Tushar,
I wanted to say that your portfolio looks amazing. I would
like to bring to your attention some typos you have.

1. WhatsaApp instead of WhatsApp
2. In the blog app section you say CURD instead of CRUD, "user" is written with a capital letter mid-sentence.

Sorry if this was not worth opening an issue, but if you are using this portfolio professionally, you should fix this.

**Comment by champ96k** [comment]
@BrunoJurkovic Thank you so much for highlighting this issue, I will fix this issue, Thanks a lot.

**Comment by champ96k** [comment]
Closing this issue fixing in version `V2.0`.
